server:
  port: 9001
    #servlet:
    #context-path: /nacos-provider
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoint:
    web:
      exposure:
        include:'*'